# Generated by Django 4.2 on 2023-05-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(default=None, null=True)),
                ("source", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=64, unique=True)),
                ("available", models.BooleanField(default=False)),
                (
                    "apartment_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("rooms", models.CharField(blank=True, max_length=32, null=True)),
                ("floor", models.CharField(blank=True, max_length=32, null=True)),
                ("area_size", models.FloatField(blank=True, null=True)),
                ("area_total_size", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
